//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rutinas
{
    public partial class DashboardMantenimiento
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Button btnSalir;

        // ── Tarjetas globales ──────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Label lblTotalEquipos;

        protected global::System.Web.UI.WebControls.Label lblVinetas2026;

        protected global::System.Web.UI.WebControls.Label lblPorcentajeGlobal;

        protected global::System.Web.UI.WebControls.Literal litBarraGlobal;

        protected global::System.Web.UI.WebControls.Label lblHoy;

        protected global::System.Web.UI.WebControls.Label lblSemana;

        // ── Filtros ────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.DropDownList ddlFiltroEmpleado;

        protected global::System.Web.UI.WebControls.Button btnSortMasSemana;

        protected global::System.Web.UI.WebControls.Button btnSortMenosSemana;

        protected global::System.Web.UI.WebControls.Button btnSortMasHoy;

        protected global::System.Web.UI.WebControls.Button btnSortMenosHoy;

        // ── Ranking ────────────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.GridView gvRanking;

        // ── Panel detalle ──────────────────────────────────────────────────
        protected global::System.Web.UI.WebControls.Panel pnlDetalle;

        protected global::System.Web.UI.WebControls.Label lblDetalleNombre;

        protected global::System.Web.UI.WebControls.Button btnCerrarDetalle;

        protected global::System.Web.UI.WebControls.GridView gvVinetas;

        protected global::System.Web.UI.WebControls.Literal litPendientes;
    }
}
